service: serverless-url-shortener

provider:
  name: aws
  apiKeys:
    - apiKey
  runtime: nodejs6.10
  stage: ${file(config.json):STAGE}
  region: ${file(config.json):REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${file(config.json):BUCKET}/*"

functions:
  create:
    handler: create/handler.handle
    events:
      - http:
          path: /
          method: get
  store:
    handler: store/handler.handle
    events:
      - http:
          path: /
          method: post
          private: true

resources:
  Resources:
    ServerlesslyRedirectS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${file(config.json):BUCKET}
        AccessControl: PublicRead
